### PR TITLE
Fix/stats

### LINKED ISSUE #37: Fix: Empty Stats
Small fix for empty lists in the Single Dog page.

### PR DESCRIPTION
**Pull request by hugh-burgess**
- Fixed empty lists for new friends to display "none listed" if none given initially.

### CODE REVIEW

File: client/src/components/create-page/CreateProfile.js [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+      method: "PUT",
+      body: formData,
+    })
+      .then((response) => response.json())
+      .then((result) => {
+        setImagePublicId(result.public_id);
+        setImageType(result.format);
+        setImageId(result.created_at);
+        setInfo(result);
+        console.log("Success:", result);
```
Comment (FriederikeM) [inline client/src/components/create-page/CreateProfile.js:37]: 👀

File: client/src/components/create-page/CreateProfile.js [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+        if (result.error.message === "Missing required parameter - file") {
+          alert("Please select a picture to upload.");
+        }
+      })
+      .catch((error) => {
+        console.error("Error:", error);
```
Comment (FriederikeM) [inline client/src/components/create-page/CreateProfile.js:43]: does this just log the error in the console? Maybe you could do an alert with an error message or direct to an error page

File: client/src/components/friends-page/CloudRight.js [hunk 3]
```diff
@@ -15,7 +15,7 @@ export default function CloudRight({
     <div className="cloud-wrapper">
       <div className="cloud-right">
         <Link to={`/single-dog/${id}`}>
-          <img className="dog-image-right" src={friend.imgSrc} alt="dog" />
+          {/* <img className="dog-image-right" src={friend.imgSrc} alt="dog" /> */}
```
Comment (FriederikeM) [inline client/src/components/friends-page/CloudRight.js:18]: Is this still needed? else -> 🗑️

File: client/src/components/single-dog/SingleDog.js [hunk 4]
```diff
@@ -10,32 +13,33 @@ import { FaBone } from "react-icons/fa";
...
-    newFriend.isStarred = !newFriend.isStarred;
+    filteredFriend.isStarred = !filteredFriend.isStarred;
     const veryNewFriends = [
       ...friends.slice(0, index),
-      newFriend,
+      filteredFriend,
       ...friends.slice(index + 1),
     ];
     setFriends(veryNewFriends);
+    console.log(veryNewFriends);
```
Comment (FriederikeM) [inline client/src/components/single-dog/SingleDog.js]: 🗑️

File: client/src/components/single-dog/Whistle.js [hunk 5]
```diff
@@ -1,45 +1,35 @@
...
-  }, []);
-
-  let { id } = useParams();
-
-  const singleDog = friends.filter((dog, index) =>
-    id.includes(index + dog.name)
+  const friend = getSingleDogFromLocalStorage(
+    Number(location.pathname.slice(9))
   );
+  console.log(friend);
```
Comment (FriederikeM) [inline client/src/components/single-dog/Whistle.js]: 👀 🗑️

**Review by FriederikeM — APPROVED** [review]
LGTM, left a few comments
